# Generated by Django 3.0 on 2021-11-28 13:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=150)),
                ('first_names', models.CharField(max_length=150)),
                ('contact_number', models.CharField(max_length=15)),
                ('age', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(5)])),
                ('date', models.DateField()),
                ('favourite_food', models.CharField(max_length=255)),
                ('likes_to_eat_out', models.PositiveSmallIntegerField()),
                ('likes_to_watch_movies', models.PositiveSmallIntegerField()),
                ('likes_to_watch_tv', models.PositiveSmallIntegerField()),
                ('likes_listening_to_radio', models.PositiveSmallIntegerField()),
                ('is_deleted', models.BooleanField(default=0)),
            ],
        ),
    ]
